parameters:
#    proyecto_back.example.class: Proyecto\BackBundle\Example

services:
#    proyecto_back.example:
#        class: %proyecto_back.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
